build: false
platform:
  - x64
clone_folder: C:\projects\php-project-workspace


## Build matrix for lowest and highest possible targets
environment:
  matrix:
  - dependencies: lowest
    php_ver_target: 7.0
  - dependencies: current
    php_ver_target: 7.0
  - dependencies: highest
    php_ver_target: 7.0

## Cache composer bits
cache:
    - '%LOCALAPPDATA%\Composer\files -> composer.lock'

## Set up environment varriables
init:
    - SET COMPOSER_ROOT_VERSION=dev-master ## Temporary until we tag first versions
    - SET PATH=C:\Program Files\OpenSSL;C:\tools\php;%PATH%
    - SET COMPOSER_NO_INTERACTION=1
    - SET ANSICON=121x90 (121x90)

## Install PHP and composer, and run the appropriate composer command
install:
    - ps: appveyor-retry cinst -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $Env:php_ver_target | Select-Object -first 1) -replace '[php|]','')
    - cd C:\tools\php
    - copy php.ini-production php.ini /Y
    - echo date.timezone="UTC" >> php.ini
    - echo extension_dir=ext >> php.ini
    - echo extension=php_openssl.dll >> php.ini
    - echo extension=php_mbstring.dll >> php.ini
    - echo extension=php_fileinfo.dll >> php.ini
    - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar
    - cd C:\projects\php-project-workspace
    - IF %dependencies%==lowest appveyor-retry C:\tools\php\composer.phar update --prefer-lowest --no-progress -n
    - IF %dependencies%==current appveyor-retry C:\tools\php\composer.phar install --no-progress
    - IF %dependencies%==highest appveyor-retry C:\tools\php\composer.phar update --no-progress -n
    - C:\tools\php\composer.phar show

## Run the actual test
test_script:
    - C:\projects\php-project-workspace\vendor\bin\phpunit -c C:\projects\php-project-workspace\phpunit.xml.dist
